const AUTH_STACK = 'AUTH_STACK';
const PUBLIC_STACK = 'PUBLIC_STACK';
const SIGN_UP = 'SIGN_UP';
const SIGN_IN = 'SIGN_IN';
const OTP = 'OTP';
const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
const REFERRAL_CODE = 'REFERRAL_CODE';
const SECURITY = 'SECURITY';
const BOTTOM_TAB = 'BOTTOM_TAB';
const HOME = 'HOME';
const CHAT = 'CHAT';
const DASHBOARD = 'DASHBOARD';
const NEWS = 'NEWS';
const SETTING = 'SETTING';
const NOTIFICATION = 'NOTIFICATION';
const PERSONAL_INFORMATION = 'PERSONAL_INFORMATION';
const EMPLOYEEPROFILE = 'EMPLOYEEPROFILE';
const DETAIL_CUSTOMER = 'DETAIL_CUSTOMER';
const NEW_CUSTOMER = 'NEW_CUSTOMER';
const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
const FILTER_INSURANCE = 'FILTER_INSURANCE';
const PRODUCT = 'PRODUCT';
const DETAIL_PRODUCT = 'DETAIL_PRODUCT';
const BUYER = 'BUYER';
const RECEIVER = 'RECEIVER';
const PAYMENT = 'PAYMENT';
const DETAIL_NEWS = 'DETAIL_NEWS';
const SYSTEM_INFOMATION = 'SYSTEM_INFOMATION';
const SECURITY_SETTING = 'SECURITY_SETTING';
const LINK = 'LINK';
const SCAN = 'SCAN';
const CONTRACT = 'CONTRACT';
const DETAIL_CONTRACT = 'DETAIL_CONTRACT';

export {
  SIGN_UP,
  OTP,
  CREATE_ACCOUNT,
  REFERRAL_CODE,
  SECURITY,
  SIGN_IN,
  BOTTOM_TAB,
  HOME,
  CHAT,
  DASHBOARD,
  NEWS,
  SETTING,
  NOTIFICATION,
  PERSONAL_INFORMATION,
  EMPLOYEEPROFILE,
  AUTH_STACK,
  PUBLIC_STACK,
  DETAIL_CUSTOMER,
  NEW_CUSTOMER,
  UPDATE_CUSTOMER,
  FILTER_INSURANCE,
  PRODUCT,
  DETAIL_PRODUCT,
  BUYER,
  RECEIVER,
  PAYMENT,
  DETAIL_NEWS,
  SYSTEM_INFOMATION,
  SECURITY_SETTING,
  LINK,
  SCAN,
  CONTRACT,
  DETAIL_CONTRACT,
};
